### ISSUE TITLE
Don't let documents created with processDocuments die before translation is complete

### ISSUE THREAD

**Issue by simonster** [zotero/zotero-connectors#10]
In https://forums.zotero.org/discussion/30588/, things are presumably breaking because we are reusing the same iframe for multiple document loads, so the old document dies when a new document gets loaded. We should either fix this by creating a new iframe for each load (as I think we do in Firefox) or by switching to HTML XHR (zotero/zotero#348) in which case we wouldn't have to worry about document lifetimes.

**Comment by adomasven** [comment]
No longer the case

**Comment by adomasven** [comment]
I was wrong. Report: https://forums.zotero.org/discussion/67143/connector-problem-with-taylor-and-francis-site

Complicated because T&F translator calls `HTTP.doPost()` within their document processors, causing a sync return from the function and we remove the iframe from the DOM. Chrome seems to not garbage collect the doc object even when it is removed from the DOM, but Firefox does. The simple solution here is to wait for translation to be complete, but currently `processDocuments()` is translation agnostic, so we'd have to entangle translation state into the function, which is pretty awful.

**Comment by dstillman** [comment]
I have this fixed locally by using HTML XMLHttpRequest for same-origin `processDocuments()`, as discussed in https://github.com/zotero/zotero/issues/348. Will share soon.

**Comment by adomasven** [comment]
Closed with f89846b8e51066f1754db142d4b2acc62713f73d
