### ISSUE TITLE
Blacklist PubMed API from proxying

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#219]
Explained here:

https://forums.zotero.org/discussion/comment/300389/#Comment_300389

I tried to do this via `_isBlacklisted()` in proxy.js but it seems like that's only used to determine whether to add an entry for a site, not for whether to proxy a URL that matches an existing proxy entry (in this case, `eutils.ncbi.nlm.nih.gov` matching `www.ncbi.nlm.nih.gov` — I'm not sure how that's happening but I guess we match on sibling subdomains?).

**Comment by adomasven** [comment]
> (in this case, eutils.ncbi.nlm.nih.gov matching www.ncbi.nlm.nih.gov — I'm not sure how that's happening but I guess we match on sibling subdomains?).

It's a bit more complicated. Since the save is happening from behind a proxy, every call to ZU.doGet(url) calls [translate.resolveURL()](https://github.com/adomasven/zotero/blob/819be60796d2b8b0b512a6d157533b5a1fe81873/chrome/content/zotero/xpcom/utilities_translate.js#L324), which, if the translation is happening from behind a proxy and unless disabled via the function argument, [proxifies the URL](https://github.com/adomasven/zotero/blob/2bc44dddd19d6bbaef59c5524c251d226c2bcdb2/chrome/content/zotero/xpcom/translation/translate.js#L1450-L1457)

We could blacklist it within the connector, but I think the proper way to resolve this is by exposing the `dontProxy` pref in translators and adjusting this within the Pubmed translator if there's no reason to run the API calls via a proxy. That would also probably mean, that we need to finally expose `Zotero.HTTP.request()` in `ZU` and deprecate `ZU.doGet()` and `ZU.doPost()`.
