### ISSUE TITLE
Target selector: continues to issue delaySync long after the save is finished

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-connectors#236]
I clicked on the Zotero button to save an article, then switched to another tab. In the background I see that the tab where the target selector is still open is continuing to issue `delaySync` calls.

**Comment by dstillman** [comment]
After the fix in 9cef1a8d6308e48dc104b485f63104573a7aaa8b, this should only happen if your mouse cursor is over the panel when you switch to the other tab. In that case, `mouseleave` is never called, so `delaySync` interval keeps happening.

We should probably fix that, but to do so we'll need to call `sendMessage('progressWindowIframe.mouseleave')` on the old tab when another tab gets focus. And ideally we would not call it when switching to another window (Chrome or otherwise). (There's some `blurred` stuff in there now that's supposed to keep the popup opening when Cmd-Tabbing to another program without moving the mouse out of the frame, but that may not be working now.)
