### ISSUE TITLE
Buggy icon on APA PsycNET in Firefox

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#251]
The icon is doing weird things for me in Firefox on APA PsycNET (which all JS-based) — sometimes I'm getting the red Z, sometimes the webpage icon, sometimes a previous folder icon on an article page… I can usually get the right icon by switching tabs and then switching back. It seems to work better in Chrome.

**Comment by adomasven** [comment]
APA PsycNET translation when navigating normally is absolutely buggy on both Chrome and Firefox, they just display different icons. Refreshing seems to help sometimes. I was getting a disabled button in Firefox intermittently, but it is not happening for me anymore.

**Comment by adomasven** [comment]
I fixed the connector failure to rerun detection on APA PsycNET navigation, and translation works on item pages, but not on the search page, where the translator calls `selectItems()` with an empty array.

Once we release the fix for the connectors, at least for the Firefox Beta, someone should look at the translator (at least an issue should be created in the translator repo)
