### ISSUE TITLE
Google docs integration feature request

### ISSUE THREAD

**Issue by MavropaliasG** [zotero/zotero-connectors#263]
Hello, thank you so much for the amazing job you are doing. Zotero is by far the best citation manager.

I am beginning to migrate all my academic work to Google Docs since the Zotero connector can now work with Google Docs. Some things that I would love to see in the Google docs integration:

- Good performance for large documents with many references (>50).
- Add the ability to identify citations in text copied in Google Docs between different documents.
- Add a way to upload a .docx or .odt in Google Docs and have Zotero identify all the existing citations (and also the opposite, to allow Zotero identify citations in a .docx or .odt that was downloaded from Google docs).

Are those planned for future releases (or even possible?)? Will we see them soon or no ETA provided?

Thank you once more.

**Comment by adomasven** [comment]
Please post all feature requests and bug reports to the [Zotero Forums](https://forums.zotero.org). See [CONTRIBUTING.md](https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md) and [How Zotero Support Works](https://www.zotero.org/support/zotero_support) for more info.

> Good performance for large documents with many references (>50).

We are looking for options to improve the speed, but cannot make any promises on this front, due to the limits of Google Docs itself.

> Add the ability to identify citations in text copied in Google Docs between different documents.

We haven't fully explored how technically feasible this is, but we suspect it might be. Either way there are no plans for the near future.

> Add a way to upload a .docx or .odt in Google Docs and have Zotero identify all the existing citations (and also the opposite, to allow Zotero identify citations in a .docx or .odt that was downloaded from Google docs).

It's [in the works](https://github.com/zotero/zotero/pull/1501)

**Comment by MavropaliasG** [comment]
Thank you @adomasven I love your work
