### ISSUE TITLE
[Chrome] DOI translator broken on HTTPS pages

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero-connectors#28]
CrossRef API can only be accessed over HTTP (to the best of my knowledge anyway), so we can't use protocol-relative URLs to load metadata from CrossRef.

Re https://forums.zotero.org/discussion/42279/american-economic-association-pages-stopped-working-in-chrome/

**Comment by aurimasv** [comment]
Is there a reason not to make _all_ GET/POST requests through the background page in connectors? We ran into an [issue with JSTOR translator](https://forums.zotero.org/discussion/43056/saving-jstor-items) where a POST request to same origin gets redirected to different origin (HTTPS from HTTP) and fails. There's no way for us to predict the redirect, so why not perform all requests in the background page?

**Comment by simonster** [comment]
In Chrome, we could probably make all requests through the background page. In Safari we have to make same-origin requests through the content script and cross-origin requests through the background page because requests from the background page don't get cookies, but it's not possible to make cross-origin requests through the content script. But I believe Chrome will send cookies with requests through the background page.

If I'm understanding correctly, the easiest fix is probably to tweak [this bit](https://github.com/zotero/zotero-connectors/blob/master/src/common/http.js#L42) of code to make cross-origin requests through the background page in both Chrome and Safari.

**Comment by aurimasv** [comment]
Hmmm, ok, I'll make that change for Chrome, not Safari. It's more important to maintain cookies (especially for proxies) than to avoid problems with cross-origin redirects, which are uncommon. We could perhaps alleviate the issue a bit by passing cookies from the page to the background, but that obviously doesn't cover HTTP-only cookies.
