### ISSUE TITLE
Safari's Intelligent Tracking Protection breaks the bookmarklet

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#284]
https://forums.zotero.org/discussion/comment/332216/#Comment_332216

This probably just needs to be fixed by using the iOS app instead, but we can look into whether there's a different way we can run the injected code, how the [Storage Access API](https://webkit.org/blog/8124/introducing-storage-access-api/) works (does it prompt for every site?), or whether there's a reliable way to convince Safari that zotero.org isn't a tracking site. For the Storage Access API, we would also have to see if a bookmarklet inject even counts as a trusted user click.

**Comment by adomasven** [comment]
Just looking the Storage Access API doc:

> The iframe needs to be a direct child of the top frame.

That's currently not the case, although I think it can be changed

> The iframe needs to be processing a user gesture at the time of the API call.

The bookmarklet invocation will not count, especially since the save is an async action, although we could display "Authenticate with zotero.org" button in the progress window (technically over the progress window, since it is a different frame). 

Currently the API does not prompt the user for access, since presumably they've already interacted with the frame:

> We have decided not to prompt the user when an iframe calls the Storage Access API to make the user experience as smooth as possible.

I could take this up if we decide the priority is high enough.

**Comment by dstillman** [comment]
> We have decided not to prompt the user when an iframe calls the Storage Access API to make the user experience as smooth as possible.

This is in the original document, but a [later version of ITP](https://webkit.org/blog/8311/intelligent-tracking-prevention-2-0/) added a prompt.

**Comment by adomasven** [comment]
There is some movement on Safari's front in regard to [treating localhost as mixed context](https://bugs.webkit.org/show_bug.cgi?id=171934) in a positive direction (#268). If we could enable saving into a local instance of Zotero it would address all desktop Safari users. That would still leave the mobile users stranded though.

**Comment by dstillman** [comment]
No more bookmarklet
