### ISSUE TITLE
Connectors do not save attachments on some sites

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero-connectors#3]
**Issue**:
When using Chrome/Safari connectors and saving certain items (typically while using a proxy), attachments are sometimes not downloaded.

This is a long-standing issue and a big reason preventing people from using Chrome or Safari connectors.

Some more details from what I was able to figure out (and Simon and Dan certainly already know):

When saving via connect, the connector sends an HTTP request to Standalone Zotero, which is acting as a server. In this request, Zotero sends all the info that it scrapped for the item, including urls for any attachments. Additionally, in this request Zotero includes the source URL and all the cookies for that domain (including cookies for higher level domains).

When Zotero Standalone receives the request to save the item, it attempts to fetch the attachments. It attaches the cookie that was passed down from the connector to any requests that have the same domain as the URL supplied by the connector. If the domain does not matched, no cookie is attached.

Typically, if an attachment is at a different domain and a cookie is not attached, this is not a big deal, but when content is restricted and accessed via proxy (or by logging in on a website), this prevents the attachment from being downloaded.

**Example**:
http://search.ebscohost.com/login.aspx?direct=true&db=aph&AN=84204840&site=ehost-live (Modernist Short Stories by Women by UTELL, JANINE) or any other EBSCOhost article with PDF
The actual entry for the article (after logging in or accessing through proxy) is located on the web.ebscohost.com domain, but the PDF is stored on the content.ebscohost.com domain. The PDF fails to download, because Zotero does not attach a cookie.

**Possible solutions**:
1) Zotero Standalone could relax the security and send cookies to different subdomains. While this would solve the problem at hand, I don't think it's a solution, since security is always a major concern. I don't think we want to be leaking any sensitive information.

2) Instead of Zotero Standalone trying to fetch attachments directly, Zotero Standalone could use the Connector (and possibly the Bookmarklet) as a proxy to retrieve content. The Connector would be able to handle all of the cookies natively.

One thing that I was concerned with was how do we establish such communication without having the connector act as a server (listen on a set port)? I'm not sure if some of these are real concerns, but: I don't think you want the connector acting as a general proxy for a malicious program trying to communicate with the internet and I don't think listening on a particular port would be possible via bookmarklet. I was thinking that we could solve this by having Zotero Standalone (or zotero translation server) determine which attachments (snapshots and/or PDFs) need to be fetched and then return a status code indicating that the connector should additionally supply attachments (with the list of attachments in the response). The connector would then send these files in a subsequent HTTP request. Zotero Standalone (or perhaps the connector) would provide an identifier to map requested attachments to items being saved. This would allow Standalone to only request files that are listed as item attachments, so I think from a security standpoint, this would not be very bad.

3) Connectors could pass cookies to Zotero Standalone in a more granular fashion (i.e. split up cookies for each level of the domain). I see that this would be possible in Chrome via [chrome.cookie API](http://developer.chrome.com/extensions/cookies.html) and in Firefox via [nsICookieManager2](https://developer.mozilla.org/en-US/docs/XPCOM_Interface_Reference/nsICookieManager2), but I didn't find anything of the sort for Safari and I'm fairly certain this would be impossible for the bookmarklet.

I'm sure there are other solutions that we can think of, so I wanted to start this issue to figure out how we can finally bridge this gap between Connectors and Firefox Plug-in. So far I think solution 2 is a very feasible option with limited drawbacks if executed correctly.

**Comment by adomasven** [comment]
Partially addressed with https://github.com/zotero/zotero/commit/091c5c279c01453fc00173ba67f541ab5e7f45e2

> Example:
> http://search.ebscohost.com/login.aspx?direct=true&db=aph&AN=84204840&site=ehost-live (Modernist Short Stories by Women by UTELL, JANINE) or any other EBSCOhost article with PDF
The actual entry for the article (after logging in or accessing through proxy) is located on the web.ebscohost.com domain, but the PDF is stored on the content.ebscohost.com domain. The PDF fails to download, because Zotero does not attach a cookie.

This was broken on connectors due to cookieManager not being initialised without providing an URI. It could have been fixed by either doing some refactoring on the cookieManager, which may be due at this point or after Z4FX deprecation, or by simply passing the import url to standalone from connectors. I've gone with the latter as there seems to be other issues with the cookieManager:

> When I try saving a reference with an attachment available (for example http://www.sciencedirect.com.ezproxy.library.uq.edu.au/science/article/pii/S116103011000047X), the PDF is not saved if Standalone is open, but everything works fine if Zotero is closed or open in Firefox.

This proxied link doesn't import attachments on both Z4FX and with connectors. A lengthier investigation is required, but this may be due to complex URL layout of sciencedirect or issues with the way we provide cookies on requests/handle redirects.

**Comment by adomasven** [comment]
Closing. We're not really getting reports for this anymore

**Comment by maurerle** [comment]
Sorry to bring this up again.
Saving attachments from Elsevier Sciencedirect.com through the Firefox Connector Plugin still does not work.

Related threads from the forum are:
https://forums.zotero.org/discussion/109940/zotero-is-not-saving-pdfs-from-sciencedirect/p2

I did not find this issue mentioned in any recent dev discussions, so posting here for others to see.

There should be a CAPTCHA opening, yet this did not happen for me on Zotero 7.0.15 (64-bit) on Debian with Zotero Connector 5.0.159 - I remember once seeing the endless CAPTCHA users report here:
https://forums.zotero.org/discussion/comment/470748/#Comment_470748

I am in a university network, therefore not requiring the login via institution from Elsevier, as mentioned in:
https://forums.zotero.org/discussion/comment/463841/#Comment_463841
but it still does not work.

The error messages from the Zotero Connector are:
```
[JavaScript Error: "Method saveSnapshot failed
@moz-extension://8895f292-73a9-481a-ba35-fd28efe23672/connector.js:312:49
"]

and

(3)(+0000004): HTTP POST http://127.0.0.1:23119/connector/saveSnapshot
(3)(+0000796): Connector: Method saveSnapshot failed with status 500
(1)(+0000001): Error: Method saveSnapshot failed
    @moz-extension://8895f292-73a9-481a-ba35-fd28efe23672/connector.js:312:49
(3)(+0010778): HTTP POST http://127.0.0.1:23119/connector/ping
(3)(+0000028): Connector: Method ping succeeded
```

While Zotero error messages are:

```
(1)(+0000003): Error: Downloaded file was not a supported type (PDF or EPUB) Error: Downloaded file was not a supported type (PDF or EPUB) Zotero.Attachments</this.InvalidPDFException@chrome://zotero/content/xpcom/attachments.js:1151:18 _enforceFileType@chrome://zotero/content/xpcom/attachments.js:1144:13 From previous event: saveSnapshot@chrome://zotero/content/xpcom/connector/server_connector.js:1171:43 init@chrome://zotero/content/xpcom/connector/server_connector.js:1128:29
```

Seems that the sciencedirect responds with HTML instead of the PDF here..


I have the following added to `extensions.zotero.findPDFs.resolvers` config item - but it somehow is not preferred:

`[{     "name":"Sci-Hub",     "method":"GET",     "url":"https://sci-hub.se/{doi}",     "mode":"html",     "selector":"#pdf",     "attribute":"src", "automatic":true }]`

If I remove my custom entry in `extensions.zotero.openURL.resolver` as well, my sci-hub resolver is correctly preferred and everything works well again.

**Comment by dstillman** [comment]
@maurerle: Please post all feedback and support requests in the forums — not on GitHub, and certainly not in an unrelated, closed 13-year-old thread.

We're obviously well aware of the ScienceDirect PDF/CAPTCHA issues. They'll be fixed by the latest version of the Zotero Connector and Zotero 7.1. The necessary changes will be in the 7.1 beta soon. Watch the forums for an announcement.
