### ISSUE TITLE
Incomplete "Zotero" object on first direct-to-server save attempt after browsing to a page in Firefox

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#329]
If I go to zotero.org in Firefox 82.0b6 and then click through to the forums and try to save, direct-to-server, it fails and I get this or something like it:

```
TypeError: Zotero.UI is undefined
    renderItem moz-extension://21c9a180-d997-ec42-95f0-00ccbca51900/ui/ProgressWindow.js:616
    renderProgress moz-extension://21c9a180-d997-ec42-95f0-00ccbca51900/ui/ProgressWindow.js:590
    renderProgress moz-extension://21c9a180-d997-ec42-95f0-00ccbca51900/ui/ProgressWindow.js:590
    render moz-extension://21c9a180-d997-ec42-95f0-00ccbca51900/ui/ProgressWindow.js:709
    React 14
    updateProgress moz-extension://21c9a180-d997-ec42-95f0-00ccbca51900/ui/ProgressWindow.js:215
    componentDidMount moz-extension://21c9a180-d997-ec42-95f0-00ccbca51900/ui/ProgressWindow.js:109
    messageListener moz-extension://21c9a180-d997-ec42-95f0-00ccbca51900/messaging_inject.js:119
    init moz-extension://21c9a180-d997-ec42-95f0-00ccbca51900/messaging_inject.js:129
react-dom.js:125:24
```

Not limited to this site, and not specific to `Zotero.UI` — I've also seen it for `Zotero.Messaging` and `Zotero.Debug`. If I log the `Zotero` object beforehand, it has most properties, but not all, and I didn't notice any pattern in which ones it has or doesn't have. If I reload the page, saving works.

**Comment by adomasven** [comment]
Seems like there's some issues with extensions in the current FX beta. In 82.0b7 I do not reproduce this, but there's some other brokenness too.

**Comment by adomasven** [comment]
So FX 82 is now out and I am still seeing bugs, including the one above, when attempting to reproduce https://forums.zotero.org/discussion/85161/firefox-connector-n-no-dropdown-categories

Idk if this is the same issue that these people have been reporting since the first message is over a month old, but it needs investigating. A search of bugzilla doesn't seem to find anything about this but I can't imagine it not being upstream.

**Comment by dstillman** [comment]
82 is out today, though.

**Comment by dstillman** [comment]
I can certainly reproduce in 82.

**Comment by adomasven** [comment]
I can reproduce this all the way to ESR 68 on arxiv.org when using the "More" option in the collection dropdown.

**Comment by dstillman** [comment]
I see this in the page console:

<blockquote>Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). sandbox eval code:663:42</blockquote>

**Comment by adomasven** [comment]
Also the problem is intermittent and can be reliably neutralized if you set a conditional breakpoint on the lines that fail checking for the existence of the object. The breakpoint triggers, but the console reports that the object is there and if you simply allow JS to continue running no problems occur. Wild.

**Comment by dstillman** [comment]
CSP error probably isn't related. I don't see that on arXiv, but can definitely reproduce this there.
