### ISSUE TITLE
Don't try to save snapshot for PDF

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#343]
1) Go to https://bitcoin.org/bitcoin.pdf in Chrome.
2) Click the save button, which will be a PDF icon.

A PDF line shows up, but a "Snapshot" line shows up below it. Two requests are sent to Zotero — a /saveSnapshot and a /saveSingleFile. Both have `pdf: true`. The latter results in an immediate `201 Created` without anything actually being created.

I didn't check, but I'm guessing this is related to the double-save problem that some people were reporting and that @fletcherhaz put a fix for the client into. If so, it seems like that was the wrong fix, and the Connector needed to be fixed to not inject SingleFile on PDF pages. One way or another, "Snapshot" shouldn't appear in the save popup and /saveSingleFile shouldn't be sent.

**Comment by fletcherhaz** [comment]
The previous double-save problem was a race condition with saving both the PDF and a Snapshot, but the PDF took a long time. It would then save two copies of the Snapshot.

I'm not sure this ever worked although I'm not sure how we didn't see it. Here what is happening is that the client is kicking off a `importFromURL` for the PDF, but returning `saveSingleFile: true` to the connector, because the client supports SingleFile. We can fix this on either end or both. Pull requests are forthcoming.
