### ISSUE TITLE
MS Edge extension

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#42]
http://www.theverge.com/2016/3/17/11255412/windows-10-microsoft-edge-browser-extensions-beta

**Comment by RAG2ko** [comment]
FYI, Microsoft recently released a toolkit to port extensions from chrome to edge:

[https://www.microsoft.com/en-us/store/p/microsoft-edge-extension-toolkit/9nblggh4txvb](url)

Hopefully this makes it easier to get Zotero running on edge.

**Comment by KrisJanssen** [comment]
Hi guys,

I have a running toolchain to create such extensions.

Currently, my only public showing of relevant experience is here:

http://stackoverflow.com/questions/4086891/how-to-debug-c-sharp-bho-project-in-visual-studio-internet-explorer/24206945#24206945

I have previously created quite a number of IE Add-ons for-hire and I will have time to invest in this from Feb onwards.

I really like Zotero and if I could help out, that'd be a nice experience.

The only caveat might be that my previous projects were primarily C# jobs and efforts such as these will likely require some know how on the intricacies of js but I'd like to have a go nonetheless.

I might start by indeed porting the existing Chrome extension?

**Comment by dstillman** [comment]
@KrisJanssen: Thanks for the offer of help! I should clarify here — we certainly don't want to create a new Edge extension. The goal would basically be to update the build script (or add a new folder to https://github.com/zotero/zotero-connectors/tree/master/scripts) to generate an Edge extension from the Chrome/Firefox code. If some files need minor modifications or alternatives, we could do that, but ideally any differences would be minimal. By contrast, currently the Safari extension is a separate extension, sharing some common code but then with a substantial amount of dedicated code. I don't see us maintaining an alternative version of that scope for Edge. My understanding is that it's not supposed to be necessary, but I'm not sure what the state of the compatibility layer is.

**Comment by adomasven** [comment]
Just to add to what @dstillman said, I looked into porting the extension a couple of months ago, but with the current state of Edge support for Browser Extensions API and the Edge Developer Toolchain being very buggy and annoying to work with, I didn't pursue this (the developer tool bugginess may have very well come from me trying to develop on a Virtual Machine, but that isn't really an excuse for Windows).

So while in theory this should be as simple as updating the build script, in reality there are a bunch of API incompatibilities (or APIs on Edge missing completely) that would need to be resolved first. We do still invite any offer to help, but be aware that working this out may be less to do with knowledge and more to do with perseverance with the current state of Edge.

**Comment by KrisJanssen** [comment]
Looking at things, I think it might indeed be that the Edge API is not yet complete enough. In any case, I like these kinds of puzzels :) I will look into this a bit as a little study project.

**Comment by adomasven** [comment]
Feel free to post here or on the [mailing list](https://groups.google.com/forum/#!forum/zotero-dev) if you feel like it's doable but are getting stuck. We'll answer any questions. I've also submitted a pull request for an improved [readme.md](https://github.com/adomasven/zotero-connectors/blob/5e32248f1cae3b9071ddf3b3ef248b88425734cd/README.md). You might want to read that - I've added information about the general architecture of the connectors to help getting started with development.

**Comment by adomasven** [comment]
I've spent some time assessing the state of Edge. Things have improved a little bit since last November, but not considerably so. After passing the extension through [Microsoft Edge Extension Toolkit](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/porting-chrome-extensions) I managed to load it and the preferences page worked.

However, I ran into the following issues:
1. Edge starts hoarding memory, slowing down and eventually crashes in VirtualBox when using the developer tools
1. `chrome.windows.get` does not respond
1. `chrome.windows.create` crashes Edge when used in `background.js`. If ran from developer toolbox it works fine
1. `document.evaluate` throws an _unspecified error_ when run in an iframe.

2 and 3 are required for the select dialog. 4 is xpath evaluation, which is required for pretty much every translator. 1 is a general nuisance that makes working with Edge very unpleasant, very fast

If you are heavily invested in having this Edge extension work, I invite you to report these issues on [Edge issue tracker](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/) and see if you get a response.

**Comment by adomasven** [comment]
I've also pushed the changes that make this extension more functional on Edge. Find them here https://github.com/adomasven/zotero-connectors/tree/feature/edge-workarounds

**Comment by adomasven** [comment]
Seems that [Chrome Edge](https://blogs.windows.com/msedgedev/2019/04/08/microsoft-edge-preview-channel-details/#eOUddWlu3Wdjg3eJ.97) makes all of this moot. The chrome app store installed extension works flawlessly from my short test. Not closing since we might eventually want to submit the extension to the Edge store too.

**Comment by lychichem** [comment]
> Seems that [Chrome Edge](https://blogs.windows.com/msedgedev/2019/04/08/microsoft-edge-preview-channel-details/#eOUddWlu3Wdjg3eJ.97) makes all of this moot. The chrome app store installed extension works flawlessly from my short test. Not closing since we might eventually want to submit the extension to the Edge store too.

Now Microsoft have opened submission to every developer, do you have any plan to submit? Because Chrome App Store is not avalible from some countries (like China), users from these countries are looking forward to Microsoft Edge extension store

**Comment by adomasven** [comment]
We haven't announced it yet, but it's available at [Zotero | Downloads](https://www.zotero.org/download/) if you visit with Edgium.
