### ISSUE TITLE
Error opening new tab in Firefox

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#76]
> Extension error: Error: Type error for parameter createProperties (Property "openerTabId" is unsupported by Firefox) for tabs.create

I'm guessing this isn't necessary in Firefox anyway due to the tab jumpback behavior.

**Comment by adomasven** [comment]
> I'm guessing this isn't necessary in Firefox anyway due to the tab jumpback behavior.

After a better examination I am not sure what you mean by Firefox's jumpback behaviour. Firefox never jumps back to the original tab for me (specifically, because `chrome.tabs.create()` is called from the background script). Best I can do now is open a tab after the current one. After closing the created tab firefox switches to whatever is the next tab in the tab list.
