### ISSUE TITLE
zotero: link being launched on first new tab in Firefox

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#78]
No idea what's going on here. Firefox 50.1 Unbranded, no other extensions.

Steps to reproduce:

1) Remove extension.

2) Load Temporary Add-on.

3) Cmd-T

Result:

![screen shot 2017-01-07 at 5 34 14 pm](https://cloud.githubusercontent.com/assets/783082/21746514/c3bb6ec6-d515-11e6-99b1-6821092ae1a0.png)

**Comment by adomasven** [comment]
I cannot reproduce this. Steps:

1. Remove addon in _about:addons_
2. Refresh _about:addons_, otherwise the extension does not disappear from the list in _about:debugging_
3. Load the extension by clicking 'Load Temporary Add-on' in _about:debugging_
4. Cmd-T does not produce any unexpected behaviour.

**Comment by dstillman** [comment]
I was afraid of that. Can you point me to any code that runs on new tabs so I can try to track this down?

**Comment by dstillman** [comment]
(And the refresh isn't necessary to reproduce. Appearance in about:debugging is only cosmetic.)

**Comment by dstillman** [comment]
False alarm. The problem was entirely unrelated to the connector, caused by a zotero:// URL that had made it into the top sites in the Firefox new-tab page in a couple different test profiles (which seems like a Firefox bug...).
